SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `grade_6` (
  `Question_ID` int(16) NOT NULL,
  `Subject_Name` varchar(255) NOT NULL,
  `Question_Title` text NOT NULL,
  `Option_1` varchar(255) NOT NULL,
  `Option_2` varchar(255) NOT NULL,
  `Option_3` varchar(255) NOT NULL,
  `Option_4` varchar(255) NOT NULL,
  `Correct_Option` int(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `grade_6` (`Question_ID`, `Subject_Name`, `Question_Title`, `Option_1`, `Option_2`, `Option_3`, `Option_4`, `Correct_Option`) VALUES
(1, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(2, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(3, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(4, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(5, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(6, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(7, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(8, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(9, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(10, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(11, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(12, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(13, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(14, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(15, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(16, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(17, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(18, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(19, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(20, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(21, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(22, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(23, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(24, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(25, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(26, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(27, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(28, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(29, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(30, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(31, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(32, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(33, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(34, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(35, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(36, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(37, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(38, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(39, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(40, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(41, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(42, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(43, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(44, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(45, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(46, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(47, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(48, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(49, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(50, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(51, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(52, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(53, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(54, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(55, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(56, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(57, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(58, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(59, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(60, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(61, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(62, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(63, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(64, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(65, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(66, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(67, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(68, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(69, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(70, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(71, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(72, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(73, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(74, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(75, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(76, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(77, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(78, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(79, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(80, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(81, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(82, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(83, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(84, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(85, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(86, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(87, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(88, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(89, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(90, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(91, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(92, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(93, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(94, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(95, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(96, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(97, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(98, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(99, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(100, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3);


CREATE TABLE `grade_7` (
  `Question_ID` int(16) NOT NULL,
  `Subject_Name` varchar(255) NOT NULL,
  `Question_Title` text NOT NULL,
  `Option_1` varchar(255) NOT NULL,
  `Option_2` varchar(255) NOT NULL,
  `Option_3` varchar(255) NOT NULL,
  `Option_4` varchar(255) NOT NULL,
  `Correct_Option` int(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `grade_7` (`Question_ID`, `Subject_Name`, `Question_Title`, `Option_1`, `Option_2`, `Option_3`, `Option_4`, `Correct_Option`) VALUES
(1, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(2, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(3, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(4, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(5, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(6, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(7, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(8, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(9, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(10, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(11, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(12, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(13, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(14, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(15, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(16, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(17, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(18, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(19, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(20, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(21, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(22, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(23, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(24, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(25, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(26, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(27, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(28, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(29, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(30, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(31, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(32, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(33, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(34, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(35, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(36, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(37, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(38, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(39, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(40, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(41, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(42, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(43, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(44, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(45, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(46, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(47, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(48, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(49, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(50, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(51, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(52, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(53, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(54, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(55, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(56, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(57, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(58, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(59, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(60, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(61, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(62, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(63, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(64, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(65, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(66, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(67, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(68, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(69, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(70, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(71, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(72, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(73, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(74, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(75, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(76, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(77, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(78, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(79, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(80, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(81, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(82, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(83, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(84, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(85, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(86, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(87, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(88, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(89, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(90, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(91, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(92, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(93, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(94, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(95, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(96, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(97, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(98, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(99, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(100, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4);


CREATE TABLE `grade_8` (
  `Question_ID` int(16) NOT NULL,
  `Subject_Name` varchar(255) NOT NULL,
  `Question_Title` text NOT NULL,
  `Option_1` varchar(255) NOT NULL,
  `Option_2` varchar(255) NOT NULL,
  `Option_3` varchar(255) NOT NULL,
  `Option_4` varchar(255) NOT NULL,
  `Correct_Option` int(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `grade_8` (`Question_ID`, `Subject_Name`, `Question_Title`, `Option_1`, `Option_2`, `Option_3`, `Option_4`, `Correct_Option`) VALUES
(1, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(2, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(3, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(4, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(5, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(6, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(7, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(8, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(9, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(10, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(11, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(12, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(13, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(14, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(15, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(16, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(17, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(18, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(19, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(20, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(21, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(22, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(23, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(24, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(25, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(26, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(27, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(28, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(29, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(30, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(31, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(32, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(33, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(34, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(35, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(36, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(37, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(38, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(39, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(40, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(41, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(42, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(43, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(44, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(45, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(46, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(47, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(48, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(49, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(50, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(51, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(52, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(53, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(54, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(55, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(56, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(57, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(58, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(59, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(60, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(61, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(62, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(63, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(64, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(65, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(66, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(67, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(68, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(69, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(70, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(71, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(72, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(73, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(74, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(75, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(76, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(77, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(78, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(79, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(80, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(81, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(82, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(83, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(84, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(85, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(86, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(87, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(88, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(89, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(90, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(91, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(92, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(93, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(94, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(95, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(96, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(97, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(98, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(99, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(100, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2);


CREATE TABLE `grade_9` (
  `Question_ID` int(16) NOT NULL,
  `Subject_Name` varchar(255) NOT NULL,
  `Question_Title` text NOT NULL,
  `Option_1` varchar(255) NOT NULL,
  `Option_2` varchar(255) NOT NULL,
  `Option_3` varchar(255) NOT NULL,
  `Option_4` varchar(255) NOT NULL,
  `Correct_Option` int(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `grade_9` (`Question_ID`, `Subject_Name`, `Question_Title`, `Option_1`, `Option_2`, `Option_3`, `Option_4`, `Correct_Option`) VALUES
(1, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(2, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(3, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(4, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(5, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(6, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(7, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(8, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(9, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(10, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(11, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(12, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(13, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(14, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(15, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(16, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(17, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(18, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(19, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(20, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(21, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(22, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(23, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(24, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(25, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(26, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(27, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(28, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(29, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(30, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(31, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(32, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(33, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(34, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(35, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(36, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(37, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(38, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(39, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(40, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(41, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(42, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(43, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(44, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(45, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(46, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(47, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(48, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(49, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(50, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(51, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(52, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(53, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(54, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(55, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(56, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(57, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(58, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(59, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(60, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(61, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(62, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(63, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(64, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(65, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(66, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(67, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(68, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(69, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(70, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(71, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(72, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(73, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(74, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(75, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(76, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(77, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(78, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(79, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(80, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(81, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(82, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(83, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(84, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(85, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(86, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(87, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(88, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(89, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(90, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(91, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(92, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 1),
(93, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(94, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 2),
(95, 'English', 'Question of English', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(96, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(97, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(98, 'Science', 'Question of Science', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 4),
(99, 'Health', 'Question of Health', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3),
(100, 'Math', 'Question of Math', 'Option 1', 'Option 2', 'Option 3', 'Option 4', 3);


CREATE TABLE `session_tracker` (
  `Session_ID` varchar(32) NOT NULL,
  `Symbol_Number` varchar(10) NOT NULL,
  `Completed_Examination` tinyint(1) NOT NULL,
  `Working_Progress` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `Examination_Deadline_Time` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `student` (
  `SN` int(11) NOT NULL,
  `Name` varchar(50) NOT NULL,
  `Symbol_Number` varchar(50) NOT NULL,
  `Fathers_Name` varchar(55) NOT NULL,
  `Mothers_Name` varchar(55) NOT NULL,
  `Date_of_Birth` varchar(55) NOT NULL,
  `Address` varchar(55) NOT NULL,
  `Contact_Number` varchar(55) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `student` (`SN`, `Name`, `Symbol_Number`, `Fathers_Name`, `Mothers_Name`, `Date_of_Birth`, `Address`, `Contact_Number`) VALUES
(4, 'test', 'test', 'test', 'test', 'test', 'test', '1111111111');


ALTER TABLE `grade_6`
  ADD PRIMARY KEY (`Question_ID`);
ALTER TABLE `grade_7`
  ADD PRIMARY KEY (`Question_ID`);
ALTER TABLE `grade_8`
  ADD PRIMARY KEY (`Question_ID`);
ALTER TABLE `grade_9`
  ADD PRIMARY KEY (`Question_ID`);


ALTER TABLE `grade_6`
  MODIFY `Question_ID` int(16) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
ALTER TABLE `grade_7`
  MODIFY `Question_ID` int(16) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
ALTER TABLE `grade_8`
  MODIFY `Question_ID` int(16) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
ALTER TABLE `grade_9`
  MODIFY `Question_ID` int(16) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;


COMMIT;